/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_librarys_tools_NDKTools */

#ifndef _Included_com_librarys_tools_NDKTools
#define _Included_com_librarys_tools_NDKTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_librarys_tools_NDKTools
 * Method:    getStringFromNDK
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_librarys_tools_NDKTools_getStringFromNDK
  (JNIEnv *, jclass,jstring,jstring);

#ifdef __cplusplus
}
#endif
#endif
